"""Visualizations: SQL data views + Plotly chart factories + file export."""

from expensa.viz.charts import (
    ablation_cumulative_curve,
    ablation_leave_one_out_bar,
    bar_spend_by_category,
    bar_top_counterparties,
    calendar_heatmap,
    category_embedding_scatter,
    confusion_matrix_heatmap,
    histogram_amounts,
    income_vs_expense_chart,
    pie_chart,
    stacked_daily_by_category,
    stacked_monthly_by_category,
    stacked_weekly_by_category,
    stage_breakdown_bar,
    trend_lines,
)
from expensa.viz.data import (
    DEFAULT_SAVINGS_CATEGORIES,
    amount_distribution,
    anomalies,
    categorization_mix,
    category_period_comparison,
    daily_by_category,
    daily_calendar,
    fixed_vs_variable,
    month_to_date_pace,
    monthly_flow_by_category,
    monthly_income_vs_expense,
    period_totals,
    recurring_subscriptions,
    savings_flow,
    spend_by_category,
    top_counterparties,
    upcoming_recurring,
    weekly_by_category,
)
from expensa.viz.exporter import save_figure

CHART_BUILDERS = {
    "pie": (spend_by_category, pie_chart),
    "histogram": (amount_distribution, histogram_amounts),
    "trend": (monthly_flow_by_category, trend_lines),
    "top": (top_counterparties, bar_top_counterparties),
    "calendar": (daily_calendar, calendar_heatmap),
    "daily-stacked": (daily_by_category, stacked_daily_by_category),
}

__all__ = [
    "ablation_cumulative_curve",
    "ablation_leave_one_out_bar",
    "amount_distribution",
    "anomalies",
    "bar_spend_by_category",
    "bar_top_counterparties",
    "calendar_heatmap",
    "categorization_mix",
    "category_embedding_scatter",
    "category_period_comparison",
    "CHART_BUILDERS",
    "confusion_matrix_heatmap",
    "daily_by_category",
    "daily_calendar",
    "DEFAULT_SAVINGS_CATEGORIES",
    "fixed_vs_variable",
    "histogram_amounts",
    "income_vs_expense_chart",
    "month_to_date_pace",
    "monthly_flow_by_category",
    "monthly_income_vs_expense",
    "period_totals",
    "pie_chart",
    "recurring_subscriptions",
    "save_figure",
    "savings_flow",
    "upcoming_recurring",
    "spend_by_category",
    "stacked_daily_by_category",
    "stacked_monthly_by_category",
    "stacked_weekly_by_category",
    "stage_breakdown_bar",
    "top_counterparties",
    "trend_lines",
    "weekly_by_category",
]
